//Problem 2
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.


public class Main {

    public static void main(String[] args) {

        long f1 = 1;
        long f2 = 1;
        long f_next = 0;
        long sum = 0;

        while(f_next < 4000000) {
            if(f_next % 2 == 0) {
                sum += f_next;
            }

            f_next = f1 + f2;
            f1 = f2;
            f2 = f_next;
        }

        System.out.println(sum);
    }


}
